# The URL the site will be built for
base_url = "https://felipesere.com"

minify_html = true

[markdown]
render_emoji = true
highlight_code = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
