[build]
  publish = "public"
  command = "zola build"

[build.environment]
ZOLA_VERSION = "0.15.3"

[[redirects]]
    from = "/post/:title"
    to = "/blogs/:title"

[[redirects]]
  from = "https://wedding.felipesere.com"
  to = "https://felipesere.com/wedding"
  status = 301
  force = true
