[build]
  publish = "public"
  command = "zola build"

[build.environment]
ZOLA_VERSION = "0.15.3"

[[redirects]]
    from = "/post/:title"
    to = "/blogs/:title"

[[redirects]]
  from = "https://wedding.felipesere.com"
  to = "https://felipesere.com/wedding"
  status = 301
  force = true

[[redirects]]
  from = "/js/script.js"
  to =  "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
